version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/openfacstrack/
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=openfacstrack
      - POSTGRES_PASSWORD=openfacstrack
      - POSTGRES_DB=openfacstrack

volumes:
  postgres_data: