version: '3.7'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: gunicorn openfacstrack.wsgi:application --bind 0.0.0.0:8000 --env DJANGO_SETTINGS_MODULE=openfacstrack.settings
    volumes:
      - static_volume:/home/openfacstrack/web/static
    expose:
      - 8000
    env_file:
      - .env.prod
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=openfacstrack
      - POSTGRES_PASSWORD=openfacstrack
      - POSTGRES_DB=openfacstrack
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/openfacstrack/web/static
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: