# pull official base image
FROM python:3.8.0-alpine

# set work directory
WORKDIR /usr/src/openfacstrack

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

# install psycopg2 dependencies
RUN apk update \
    && apk add postgresql-dev gcc python3-dev musl-dev

# install dependencies
RUN pip install --upgrade pip
COPY requirements.txt /usr/src/openfacstrack/requirements.txt
RUN pip install -r requirements.txt

# copy entrypoint.dev.sh
COPY entrypoint.dev.sh /usr/src/openfacstrack/entrypoint.dev.sh

# copy project
COPY . /usr/src/openfacstrack/

# run entrypoint.dev.sh
ENTRYPOINT ["/usr/src/openfacstrack/entrypoint.dev.sh"]